"""create initial schema

Revision ID: 9c137cce3da6
Revises:
Create Date: 2026-07-25 15:52:03.409870

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "9c137cce3da6"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "garages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_garages")),
    )
    op.create_table(
        "job_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_name", sa.String(length=60), nullable=False),
        sa.Column(
            "status",
            sa.Enum("running", "success", "failed", name="jobstatus", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("items_processed", sa.Integer(), nullable=True),
        sa.Column("notifications_sent", sa.Integer(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_runs")),
    )
    op.create_index(op.f("ix_job_runs_job_name"), "job_runs", ["job_name"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "is_platform_admin", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "garage_invitations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("garage_id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("invited_by_user_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["garage_id"],
            ["garages.id"],
            name=op.f("fk_garage_invitations_garage_id_garages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["invited_by_user_id"],
            ["users.id"],
            name=op.f("fk_garage_invitations_invited_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_garage_invitations")),
        sa.UniqueConstraint("token", name=op.f("uq_garage_invitations_token")),
    )
    op.create_index(
        op.f("ix_garage_invitations_garage_id"), "garage_invitations", ["garage_id"], unique=False
    )
    op.create_table(
        "garage_members",
        sa.Column("garage_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "joined_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["garage_id"],
            ["garages.id"],
            name=op.f("fk_garage_members_garage_id_garages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_garage_members_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("garage_id", "user_id", name=op.f("pk_garage_members")),
    )
    op.create_table(
        "notification_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("garage_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("recipient", sa.String(length=255), nullable=False),
        sa.Column("reminder_key", sa.String(length=200), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum("sent", "failed", name="notificationstatus", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["garage_id"],
            ["garages.id"],
            name=op.f("fk_notification_log_garage_id_garages"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notification_log_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_log")),
        sa.UniqueConstraint("reminder_key", name=op.f("uq_notification_log_reminder_key")),
    )
    op.create_index(
        op.f("ix_notification_log_created_at"), "notification_log", ["created_at"], unique=False
    )
    op.create_table(
        "service_categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("garage_id", sa.Integer(), nullable=True),
        sa.Column("code", sa.String(length=60), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "section",
            sa.Enum(
                "documents",
                "engine",
                "transmission",
                "running_gear",
                "electrical",
                "other",
                name="categorysection",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "kind",
            sa.Enum("maintenance", "document", name="categorykind", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("default_interval_km", sa.Integer(), nullable=True),
        sa.Column("default_interval_months", sa.Integer(), nullable=True),
        sa.Column(
            "requires_fuel_types",
            sa.ARRAY(sa.String(length=40)),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "requires_gearbox_types",
            sa.ARRAY(sa.String(length=40)),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "requires_drivetrains",
            sa.ARRAY(sa.String(length=40)),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "requires_equipment",
            sa.ARRAY(sa.String(length=40)),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("hint", sa.Text(), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "default_interval_km is null or default_interval_km > 0",
            name=op.f("ck_service_categories_positive_km_interval"),
        ),
        sa.CheckConstraint(
            "default_interval_months is null or default_interval_months > 0",
            name=op.f("ck_service_categories_positive_month_interval"),
        ),
        sa.ForeignKeyConstraint(
            ["garage_id"],
            ["garages.id"],
            name=op.f("fk_service_categories_garage_id_garages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_service_categories")),
        sa.UniqueConstraint(
            "garage_id",
            "code",
            name=op.f("uq_service_categories_garage_id_code"),
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_table(
        "vehicles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("garage_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("make", sa.String(length=60), nullable=False),
        sa.Column("model", sa.String(length=60), nullable=False),
        sa.Column("generation", sa.String(length=60), nullable=True),
        sa.Column("model_year", sa.Integer(), nullable=True),
        sa.Column("registration_number", sa.String(length=20), nullable=True),
        sa.Column("vin", sa.String(length=17), nullable=True),
        sa.Column(
            "fuel_type",
            sa.Enum(
                "petrol",
                "diesel",
                "petrol_lpg",
                "hybrid_petrol",
                "hybrid_diesel",
                "plugin_hybrid",
                "electric",
                name="fueltype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("engine_code", sa.String(length=20), nullable=True),
        sa.Column("engine_displacement_cc", sa.Integer(), nullable=True),
        sa.Column("power_hp", sa.Integer(), nullable=True),
        sa.Column(
            "gearbox_type",
            sa.Enum(
                "manual",
                "torque_converter",
                "dual_clutch_dry",
                "dual_clutch_wet",
                "cvt",
                name="gearboxtype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("gearbox_gears", sa.Integer(), nullable=True),
        sa.Column(
            "drivetrain",
            sa.Enum("front", "rear", "all", name="drivetrain", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column(
            "equipment",
            sa.ARRAY(sa.String(length=40)),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("first_registration_date", sa.Date(), nullable=True),
        sa.Column("current_mileage_km", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("annual_mileage_km", sa.Integer(), nullable=True),
        sa.Column("photo_storage_key", sa.String(length=255), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["garage_id"],
            ["garages.id"],
            name=op.f("fk_vehicles_garage_id_garages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vehicles")),
        sa.UniqueConstraint("id", "garage_id", name=op.f("uq_vehicles_id_garage_id")),
    )
    op.create_index(op.f("ix_vehicles_garage_id"), "vehicles", ["garage_id"], unique=False)
    op.create_table(
        "fuel_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("garage_id", sa.Integer(), nullable=False),
        sa.Column("vehicle_id", sa.Integer(), nullable=False),
        sa.Column("filled_on", sa.Date(), nullable=False),
        sa.Column("mileage_km", sa.Integer(), nullable=False),
        sa.Column("litres", sa.Numeric(precision=7, scale=2), nullable=False),
        sa.Column("price_per_litre", sa.Numeric(precision=7, scale=3), nullable=True),
        sa.Column("total_cost", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), server_default=sa.text("'RON'"), nullable=False),
        sa.Column("is_full_tank", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("station", sa.String(length=120), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by_user_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("litres > 0", name=op.f("ck_fuel_logs_positive_litres")),
        sa.CheckConstraint("mileage_km >= 0", name=op.f("ck_fuel_logs_non_negative_mileage")),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_fuel_logs_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id", "garage_id"],
            ["vehicles.id", "vehicles.garage_id"],
            name=op.f("fk_fuel_logs_vehicle_id_vehicles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fuel_logs")),
    )
    op.create_index(op.f("ix_fuel_logs_garage_id"), "fuel_logs", ["garage_id"], unique=False)
    op.create_index(op.f("ix_fuel_logs_vehicle_id"), "fuel_logs", ["vehicle_id"], unique=False)
    op.create_table(
        "maintenance_rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("garage_id", sa.Integer(), nullable=False),
        sa.Column("vehicle_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("interval_km", sa.Integer(), nullable=True),
        sa.Column("interval_months", sa.Integer(), nullable=True),
        sa.Column("is_enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "interval_km is null or interval_km > 0",
            name=op.f("ck_maintenance_rules_positive_km_interval"),
        ),
        sa.CheckConstraint(
            "interval_months is null or interval_months > 0",
            name=op.f("ck_maintenance_rules_positive_month_interval"),
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["service_categories.id"],
            name=op.f("fk_maintenance_rules_category_id_service_categories"),
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id", "garage_id"],
            ["vehicles.id", "vehicles.garage_id"],
            name=op.f("fk_maintenance_rules_vehicle_id_vehicles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_maintenance_rules")),
        sa.UniqueConstraint(
            "vehicle_id", "category_id", name=op.f("uq_maintenance_rules_vehicle_id_category_id")
        ),
    )
    op.create_index(
        op.f("ix_maintenance_rules_garage_id"), "maintenance_rules", ["garage_id"], unique=False
    )
    op.create_index(
        op.f("ix_maintenance_rules_vehicle_id"), "maintenance_rules", ["vehicle_id"], unique=False
    )
    op.create_table(
        "mileage_readings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("garage_id", sa.Integer(), nullable=False),
        sa.Column("vehicle_id", sa.Integer(), nullable=False),
        sa.Column("recorded_on", sa.Date(), nullable=False),
        sa.Column("mileage_km", sa.Integer(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "manual",
                "fuel_log",
                "service_event",
                name="mileagesource",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("created_by_user_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "mileage_km >= 0", name=op.f("ck_mileage_readings_non_negative_mileage")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_mileage_readings_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id", "garage_id"],
            ["vehicles.id", "vehicles.garage_id"],
            name=op.f("fk_mileage_readings_vehicle_id_vehicles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mileage_readings")),
    )
    op.create_index(
        op.f("ix_mileage_readings_garage_id"), "mileage_readings", ["garage_id"], unique=False
    )
    op.create_index(
        op.f("ix_mileage_readings_recorded_on"), "mileage_readings", ["recorded_on"], unique=False
    )
    op.create_index(
        op.f("ix_mileage_readings_vehicle_id"), "mileage_readings", ["vehicle_id"], unique=False
    )
    op.create_table(
        "service_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("garage_id", sa.Integer(), nullable=False),
        sa.Column("vehicle_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("performed_on", sa.Date(), nullable=False),
        sa.Column("mileage_km", sa.Integer(), nullable=True),
        sa.Column("cost", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), server_default=sa.text("'RON'"), nullable=False),
        sa.Column("workshop", sa.String(length=120), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by_user_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "cost is null or cost >= 0", name=op.f("ck_service_events_non_negative_cost")
        ),
        sa.CheckConstraint(
            "mileage_km is null or mileage_km >= 0",
            name=op.f("ck_service_events_non_negative_mileage"),
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["service_categories.id"],
            name=op.f("fk_service_events_category_id_service_categories"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_service_events_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id", "garage_id"],
            ["vehicles.id", "vehicles.garage_id"],
            name=op.f("fk_service_events_vehicle_id_vehicles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_service_events")),
    )
    op.create_index(
        op.f("ix_service_events_garage_id"), "service_events", ["garage_id"], unique=False
    )
    op.create_index(
        op.f("ix_service_events_vehicle_id"), "service_events", ["vehicle_id"], unique=False
    )
    op.create_table(
        "vehicle_documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("garage_id", sa.Integer(), nullable=False),
        sa.Column("vehicle_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=False),
        sa.Column("provider", sa.String(length=120), nullable=True),
        sa.Column("reference_number", sa.String(length=60), nullable=True),
        sa.Column("cost", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), server_default=sa.text("'RON'"), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by_user_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "cost is null or cost >= 0", name=op.f("ck_vehicle_documents_non_negative_cost")
        ),
        sa.CheckConstraint(
            "valid_to >= valid_from", name=op.f("ck_vehicle_documents_validity_window_ordered")
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["service_categories.id"],
            name=op.f("fk_vehicle_documents_category_id_service_categories"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_vehicle_documents_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id", "garage_id"],
            ["vehicles.id", "vehicles.garage_id"],
            name=op.f("fk_vehicle_documents_vehicle_id_vehicles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vehicle_documents")),
    )
    op.create_index(
        op.f("ix_vehicle_documents_garage_id"), "vehicle_documents", ["garage_id"], unique=False
    )
    op.create_index(
        op.f("ix_vehicle_documents_valid_to"), "vehicle_documents", ["valid_to"], unique=False
    )
    op.create_index(
        op.f("ix_vehicle_documents_vehicle_id"), "vehicle_documents", ["vehicle_id"], unique=False
    )
    op.create_table(
        "attachments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("garage_id", sa.Integer(), nullable=False),
        sa.Column("vehicle_id", sa.Integer(), nullable=True),
        sa.Column("service_event_id", sa.Integer(), nullable=True),
        sa.Column("document_id", sa.Integer(), nullable=True),
        sa.Column("fuel_log_id", sa.Integer(), nullable=True),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("storage_key", sa.String(length=255), nullable=False),
        sa.Column("uploaded_by_user_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(vehicle_id is not null)::int + (service_event_id is not null)::int + (document_id is not null)::int + (fuel_log_id is not null)::int = 1",
            name=op.f("ck_attachments_exactly_one_owner"),
        ),
        sa.CheckConstraint("size_bytes > 0", name=op.f("ck_attachments_positive_size")),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["vehicle_documents.id"],
            name=op.f("fk_attachments_document_id_vehicle_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["fuel_log_id"],
            ["fuel_logs.id"],
            name=op.f("fk_attachments_fuel_log_id_fuel_logs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["garage_id"],
            ["garages.id"],
            name=op.f("fk_attachments_garage_id_garages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["service_event_id"],
            ["service_events.id"],
            name=op.f("fk_attachments_service_event_id_service_events"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_user_id"],
            ["users.id"],
            name=op.f("fk_attachments_uploaded_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicles.id"],
            name=op.f("fk_attachments_vehicle_id_vehicles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attachments")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_attachments_storage_key")),
    )
    op.create_index(
        op.f("ix_attachments_document_id"), "attachments", ["document_id"], unique=False
    )
    op.create_index(
        op.f("ix_attachments_fuel_log_id"), "attachments", ["fuel_log_id"], unique=False
    )
    op.create_index(op.f("ix_attachments_garage_id"), "attachments", ["garage_id"], unique=False)
    op.create_index(
        op.f("ix_attachments_service_event_id"), "attachments", ["service_event_id"], unique=False
    )
    op.create_index(op.f("ix_attachments_vehicle_id"), "attachments", ["vehicle_id"], unique=False)
    op.create_table(
        "service_event_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("service_event_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("brand", sa.String(length=60), nullable=True),
        sa.Column("part_number", sa.String(length=60), nullable=True),
        sa.Column(
            "quantity",
            sa.Numeric(precision=8, scale=2),
            server_default=sa.text("1"),
            nullable=False,
        ),
        sa.Column("unit_cost", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_service_event_items_positive_quantity")),
        sa.CheckConstraint(
            "unit_cost is null or unit_cost >= 0",
            name=op.f("ck_service_event_items_non_negative_unit_cost"),
        ),
        sa.ForeignKeyConstraint(
            ["service_event_id"],
            ["service_events.id"],
            name=op.f("fk_service_event_items_service_event_id_service_events"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_service_event_items")),
    )
    op.create_index(
        op.f("ix_service_event_items_service_event_id"),
        "service_event_items",
        ["service_event_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_service_event_items_service_event_id"), table_name="service_event_items")
    op.drop_table("service_event_items")
    op.drop_index(op.f("ix_attachments_vehicle_id"), table_name="attachments")
    op.drop_index(op.f("ix_attachments_service_event_id"), table_name="attachments")
    op.drop_index(op.f("ix_attachments_garage_id"), table_name="attachments")
    op.drop_index(op.f("ix_attachments_fuel_log_id"), table_name="attachments")
    op.drop_index(op.f("ix_attachments_document_id"), table_name="attachments")
    op.drop_table("attachments")
    op.drop_index(op.f("ix_vehicle_documents_vehicle_id"), table_name="vehicle_documents")
    op.drop_index(op.f("ix_vehicle_documents_valid_to"), table_name="vehicle_documents")
    op.drop_index(op.f("ix_vehicle_documents_garage_id"), table_name="vehicle_documents")
    op.drop_table("vehicle_documents")
    op.drop_index(op.f("ix_service_events_vehicle_id"), table_name="service_events")
    op.drop_index(op.f("ix_service_events_garage_id"), table_name="service_events")
    op.drop_table("service_events")
    op.drop_index(op.f("ix_mileage_readings_vehicle_id"), table_name="mileage_readings")
    op.drop_index(op.f("ix_mileage_readings_recorded_on"), table_name="mileage_readings")
    op.drop_index(op.f("ix_mileage_readings_garage_id"), table_name="mileage_readings")
    op.drop_table("mileage_readings")
    op.drop_index(op.f("ix_maintenance_rules_vehicle_id"), table_name="maintenance_rules")
    op.drop_index(op.f("ix_maintenance_rules_garage_id"), table_name="maintenance_rules")
    op.drop_table("maintenance_rules")
    op.drop_index(op.f("ix_fuel_logs_vehicle_id"), table_name="fuel_logs")
    op.drop_index(op.f("ix_fuel_logs_garage_id"), table_name="fuel_logs")
    op.drop_table("fuel_logs")
    op.drop_index(op.f("ix_vehicles_garage_id"), table_name="vehicles")
    op.drop_table("vehicles")
    op.drop_table("service_categories")
    op.drop_index(op.f("ix_notification_log_created_at"), table_name="notification_log")
    op.drop_table("notification_log")
    op.drop_table("garage_members")
    op.drop_index(op.f("ix_garage_invitations_garage_id"), table_name="garage_invitations")
    op.drop_table("garage_invitations")
    op.drop_table("users")
    op.drop_index(op.f("ix_job_runs_job_name"), table_name="job_runs")
    op.drop_table("job_runs")
    op.drop_table("garages")
    # ### end Alembic commands ###
