"""note where a corrected interval came from

Revision ID: 80040fb37ea9
Revises: e0facea9e594
Create Date: 2026-07-27 00:29:58.397302

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "80040fb37ea9"
down_revision: str | Sequence[str] | None = "e0facea9e594"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "maintenance_rules", sa.Column("source_note", sa.String(length=200), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("maintenance_rules", "source_note")
    # ### end Alembic commands ###
